export {
  PageHeaderSkeleton,
  FiltersSkeleton,
  FormFieldsSkeleton,
  TableSkeleton,
  MetricCardsSkeleton,
  ListPageSkeleton,
  DashboardPageSkeleton,
  DetailPageSkeleton,
  FormPageSkeleton,
  BillingPageSkeleton,
  PosPageSkeleton,
  InventoryPageSkeleton,
  ReceiptSkeleton,
  PlanCardsSkeleton,
  PageSkeleton,
} from './shared';
